### ISSUE TITLE
brewed recorder on Apple silicon needs updates to file locations

### ISSUE THREAD

**Issue by ckrey** [owntracks/homebrew-recorder#2]
e.g.
```
/opt/homebrew/etc/ot-recorder.sh: line 17: /usr/local/sbin/ot-recorder: No such file or directory
```

**Comment by jpmens** [comment]
I suppose we should use something like `bin` as per [the cookbook](https://docs.brew.sh/Formula-Cookbook#just-moving-some-files). Same applies to paths to Recorder's spool directory, etc.
