### ISSUE TITLE
{etc}/default/ directory doesn't exist

### ISSUE THREAD

**Issue by jpmens** [owntracks/homebrew-recorder#4]
We configure `ot-recorder` to use `#{etc}/default/ot-recorder` in https://github.com/owntracks/homebrew-recorder/blob/e854f857f21d89d7a527eeeda11bd10e9bbd0773/recorder.rb#L99 but that directory doesn't exist and we don't create it.

I wonder whether we should just use ``#{etc}/ot-recorder`  (without `/default/`) and/or add a `.default` extension to the file, though in both cases the documentation for Homebrew version would differ from non-homebred or simply create the directory and populate it with a template.

**Comment by ckrey** [comment]
on my machine the directory exists for othe packages. I think wr should create it if not already existing and populate it with a template
