### ISSUE TITLE
Critical Installation Issues and Code Errors in Homebrew Tap

### ISSUE THREAD

**Issue by stlinkgangs** [owntracks/homebrew-recorder#6]
Hello,

I want to draw your attention to the critical installation issues and frustrating code errors that I have encountered while attempting to install the owntracks/recorder formula via Homebrew. This experience has been a nightmare, causing immense frustration and wasting a significant amount of my time.

Undefined Variable or Method Causing Installation Failure:
Error: undefined local variable or method 'ot'
File: recorder.rb, line 236
This blatant mistake completely derailed the installation process, leaving me bewildered and wasting precious hours trying to figure out what went wrong

Incorrect Argument Type Resulting in Installation Failure:
Error: Service#environment_variables expects a hash
File: recorder.rb, line 238

Syntax Error - Missing "end" Statement:
Error: syntax error, unexpected end-of-input, expecting end
File: recorder.rb, line 240

This oversight should have been caught during the development and testing process, sparing users from needless confusion and troubleshooting. 

Nonetheless, I really like the owntracks project and hope that it continues long into the future.
Have a nice day

**Comment by jpmens** [comment]
Which versions of macOS and Homebrew did you use when attempting this installation?

**Comment by jpmens** [comment]
```
==> Fetching owntracks/recorder/recorder
==> Downloading https://github.com/owntracks/recorder/archive/0.9.3.tar.gz
Already downloaded: /Users/jpm/Library/Caches/Homebrew/downloads/e3fbe8f00c32d92367d0de24e7bf6210c11a876d192ea6479f0d700b350f152d--recorder-0.9.3.tar.gz
==> Installing recorder from owntracks/recorder
==> make
==> checking whether lmdb needs initializing
==> /usr/local/Cellar/recorder/0.9.3/sbin/ot-recorder --initialize
==> Caveats
    OwnTracks Recorder has been installed with a default configuration.
    You can make changes to the configuration by editing and then
    launching:
        /usr/local/etc/ot-recorder.sh

To restart owntracks/recorder/recorder after an upgrade:
  brew services restart owntracks/recorder/recorder
Or, if you don't want/need a background service you can just run:
  /usr/local/etc/ot-recorder.sh
==> Summary
🍺  /usr/local/Cellar/recorder/0.9.3: 316 files, 1MB, built in 8 seconds
==> Running `brew cleanup recorder`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

**Comment by jpmens** [comment]
Thank you for reporting this, @stlinkgangs, and I'm sorry that this happened. It definitely was a case of _not testing after editing_, for which I apologize.

I believe the package can now correctly be installed.
